# Generated by Django 5.0.3 on 2024-03-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrs', '0002_emailqr_tarjetapresentacionqr_textoqr_urlqr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailqr',
            name='redundancia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emailqr',
            name='tamaño',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tarjetapresentacionqr',
            name='redundancia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tarjetapresentacionqr',
            name='tamaño',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='textoqr',
            name='redundancia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='textoqr',
            name='tamaño',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='urlqr',
            name='redundancia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='urlqr',
            name='tamaño',
            field=models.CharField(max_length=50),
        ),
    ]
