# Generated by Django 5.0.3 on 2024-03-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='numero_celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
