# Generated by Django 4.2.4 on 2024-03-03 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QR',
            fields=[
                ('ID_QR', models.AutoField(primary_key=True, serialize=False)),
                ('Contenido', models.TextField()),
                ('Estilos', models.CharField(max_length=255)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
    ]
